### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by delt87** [owenauch/NBA-Fantasy-Optimizer#3]
'invalid syntax' error in line 348: stringify_lineup

**Comment by owenauch** [comment]
Can you fix it?

**Comment by delt87** [comment]
No I'm not sure why it's coming up with that error.  I'm using python 3.6.

**Comment by owenauch** [comment]
Try python 2 instead.

**Comment by delt87** [comment]
I'll give that a try. Do you recommend a specific build of version 2? Like
2.7? I'm new to python so I'm sure it's something simple that I'm screwing
up. I'm very interested in seeing how your model works as I've been running
a simple DFS model using linear regression in excel for the past 2 years
with some okay results.

**Comment by delt87** [comment]
As you suggested, it ran fine in python 2.  Appreciate your help.

**Comment by owenauch** [comment]
No problem, let me know if you're getting good results from the program.
